### ISSUE TITLE
其中的latex文件夹必须有的吗？

### ISSUE THREAD

**Issue by A-Pai** [GISerDaiShaoqing/Note-of-Applied-Statistics-with-R-Book#2]
1. 其中的latex文件夹必须有的吗？
2. 何处设置了要读取这个文件夹？
3. latex文件夹中的before_body.tex，after_body.tex等文件，是固定的吗？还是哪里设置了要读取这些文件？

**Comment by GISerDaiShaoqing** [comment]
那个是模板吧。bookdown默认生成的，影响不大
